name: Run packer validate

on: [pull_request]

jobs:
  packer_validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Packer
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: --syntax-only
          target: ami.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
